# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: 'install tools'
    init: 
      curl -SL https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2022-07-23/oss-cad-suite-linux-x64-20220723.tgz | tar -xzC /workspace
    command: source /workspace/oss-cad-suite/environment
